### ISSUE TITLE
Error: Expected [\n\r] but end of input found. 

### ISSUE THREAD

**Issue by annelorraineuy** [react-native-community/react-native-linear-gradient#141] opened 2017-01-13 00:19 UTC
```
rnpm-install info Linking react-native-linear-gradient android dependency 
rnpm-install info Android module react-native-linear-gradient has been successfully linked 
rnpm-install ERR! It seems something went wrong while linking. Error: Expected [\n\r] but end of input found.
Please file an issue here: https://github.com/facebook/react-native/issues 
```

I get this error after doing `react-native link react-native-linear-gradient`

```
package:
"react": "15.4.1",
"react-native": "^0.39.2"
```

**Comment by annelorraineuy** [comment] 2017-01-24 22:12
I got this to work now.

This happens when you try to `react-native link` the latest code when your react-native is still at 0.39. So I forked my own copy of the repo and reverted to the commit before the RN 0.40 update.

**Comment by dgladkov** [comment] 2017-03-30 13:06
Glad to know that the issue is resolved! Closing it.

**Closed by dgladkov** 2017-03-30 13:06 UTC

**Comment by WhynoChinese** [comment] 2017-07-28 07:05
I still have this problem, I try to react-native link and my react-native is 0.43

**Comment by master-atul** [comment] 2017-09-25 07:06
I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

**Comment by vantuan88291** [comment] 2018-12-28 08:14
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

very nice, i solved this stupid error just one line :D

**Comment by LeslieJAnderson** [comment] 2019-06-06 16:04
@master-atul, you solved my problem for a completely different library. Thank you.

**Comment by matthew-gordon** [comment] 2020-07-10 22:32
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This solved an the issue for me as well for anyone coming across this in 2020

**Comment by GermainPereira** [comment] 2020-07-20 11:24
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Worked for me :laughing: :laughing:

```
    "react": "16.13.1",
    "react-native": "0.63.0",
```

**Comment by SrBrahma** [comment] 2020-07-21 22:14
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

React Native should fix it.

**Comment by Jhoy1992** [comment] 2020-07-23 04:54
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This solved my problem when trying to link custom fonts, thanks man.

**Comment by Paulotx** [comment] 2020-07-25 22:54
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Tank you

**Comment by gabrielkesslau** [comment] 2020-07-28 02:17
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Thanks!!

**Comment by carlomigueldy** [comment] 2020-07-28 02:19
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

I wonder how you figured this out XD But thanks man!!

**Comment by guimaraesmiguel** [comment] 2020-07-30 19:06
> > I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `
> 
> I wonder how you figured this out XD But thanks man!!

I got the same issue and it solved my life, but I have the same question mark: how you figured this out. Any way, thank you very much.

**Comment by ricardopontesdantas** [comment] 2020-08-04 19:14
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Thanks!!

**Comment by lmourabraga** [comment] 2020-08-07 00:55
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This is the kind of problem we don't know why but we also don't care. Thank you for sharing the solution. :) 💯

**Comment by PrantikMondal** [comment] 2020-08-13 13:34
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Not worked for me at all. 
If i tried to link any of library to my project, my error showing something like this:

error Linking "@sentry/react-native" failed. Run CLI with --verbose flag for more details.
SyntaxError: Expected "{" but end of input found.
    at peg$buildStructuredError (C:\[Project_name]\node_modules\xcode\lib\parser\pbxproj.js:429:12)
    at Object.peg$parse [as parse] (C:\[Project_name]\node_modules\xcode\lib\parser\pbxproj.js:1891:11)
    at pbxProject.parseSync (C:\[Project_name]\node_modules\xcode\lib\pbxProject.js:63:24)
    at isInstalled (C:\[Project_name]\node_modules\@react-native-community\cli-platform-ios\build\link\isInstalled.js:43:67)
    at Object.isInstalled (C:\[Project_name]\node_modules\@react-native-community\cli-platform-ios\build\link\common\isInstalled.js:23:35)
    at Object.keys.forEach.platform (C:\[Project_name]\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:53:36)
    at Array.forEach (<anonymous>)
    at linkDependency (C:\[Project_name]\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:36:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by xialGuri** [comment] 2022-03-13 17:24
@PrantikMondal did you solve that problem? adding a  line didn't work for me neither
