### ISSUE TITLE
Invalid float runtime error

### ISSUE THREAD

**Issue by MarvinAmador7** [react-native-community/react-native-linear-gradient#115] opened 2016-10-19 21:10 UTC
node: v6.8.1
react-native-cli: 1.0.0
react-native: 0.33.0

This is happening at runtime 
![image](https://cloud.githubusercontent.com/assets/13001660/19537643/04638176-960e-11e6-98f4-56b8597ac370.png)

Any idea ? Thanks

**Comment by dgladkov** [comment] 2016-12-26 16:38
Can you please provide your usage example? This really looks like a typo in your JS code.

P.S. I am closing the issue as it's pretty old and impossible to reproduce, but please reopen it if you sill experience the problem.

**Closed by dgladkov** 2016-12-26 16:38 UTC
