### ISSUE TITLE
Gradient Angle Calculated For Square and Squashed to Fit Rectangle

### ISSUE THREAD

**Issue by kevinvangelder** [react-native-community/react-native-linear-gradient#134] opened 2016-12-28 19:53 UTC
I'm in the progress of porting this project to support Windows and to verify my implementation was correct I decided to try the following example code to see if my generated gradient matched the screenshot.

```
<LinearGradient
  start={[0.0, 0.25]} end={[0.5, 1.0]}
  locations={[0,0.4,0.6]} // I tweaked this value but it doesn't really affect the issue at hand
  colors={['#4c669f', '#3b5998', '#192f6a']}
  style={styles.linearGradient}>
  <Text style={styles.buttonText}>
    Sign in with Facebook
  </Text>
</LinearGradient>
```

Running this example against my code produced the following result, which given the start and end points seemed correct to me, but obviously is different from the screenshot in the readme.
![g31nk43n75](https://cloud.githubusercontent.com/assets/1771152/21662939/d631425a-d291-11e6-80d8-9c763020af5e.png)

Thinking maybe the screenshot associated with the code example for iOS was out of date I quickly ran the code example against the latest release and got this result:
![p7ymw70puq](https://cloud.githubusercontent.com/assets/1771152/21662944/dd77cdc2-d291-11e6-9e0d-0858e18930e3.png)

- A is the angle we expect the gradient to be perpendicular to.
- B is the angle the angle would be perpendicular to if the starting x/y coordinates were flipped.
- C is the approximate angle the gradient is actually perpendicular to.

What appears to be happening, at least on iOS, is that the gradient angle is calculated for a square and then squashed down to fit into the rectangle.
![wz0ijuhqbr](https://cloud.githubusercontent.com/assets/1771152/21662951/e299800c-d291-11e6-8780-83f153814b17.png)

In my mind this is a bug that needs to be addressed. The start/end points should be applied to the area the gradient is going to be applied to, not an arbitrary square. Is there an option that didn't get set in the Obj-C that would fix this unexpected behavior?

**Comment by george-cz** [comment] 2017-02-15 15:54
@kevinvangelder hi, have you resolved this issue somehow?

**Comment by kevinvangelder** [comment] 2017-02-15 18:51
@george-cz No, but my implementation for WPF is what I would consider to be the "correct" angle. I was hoping to get some feedback from the maintainers and/or other users if my understanding is somehow flawed, but so far I haven't received confirmation from anyone.

**Comment by george-cz** [comment] 2017-02-15 18:57
@kevinvangelder allright, well, I dug into it a bit today and it's native way how to make diagonal gradients. Its very well visible in this video https://www.youtube.com/watch?v=SgCwALXlyLQ

So its a bug (feature? didn't find any material, really) in iOS.

**Comment by dgladkov** [comment] 2017-04-07 11:22
Sorry for the long response time! I've reproduced this problem and it in fact appears only on iOS. After some investigation it appears that it's a rather obscure [CAGradientLayer's bug](http://stackoverflow.com/questions/38821631/cagradientlayer-diagonal-gradient/43176174#43176174). Quoting StackOverflow post:

> It took some time to figure out, but from careful observation, I found out that Apple's implementation of gradients in CAGradientLayer is pretty odd:
> 1. First it converts the view to a square.
> 2. Then it applies the gradient using start/end points.
> 3. The middle gradient will indeed form a 90 degree angle in this resolution.
> 4. Finally, it squishes the view down to the original size.

The only viable solution is to move from CAGradientLayer to [CGContext​Draw​Linear​Gradient](https://developer.apple.com/reference/coregraphics/1454782-cgcontextdrawlineargradient?language=objc), which is rather painful because it requires overriding UIView's `drawRect` which [RCTView does not support](https://github.com/facebook/react-native/issues/1163). We can probably work around that by using UIView to render a gradient and wrap it inside a regular View, [same as we do for Android](https://github.com/react-native-community/react-native-linear-gradient/blob/df8ce9569d0729d683a385fe081220c8efe8dc66/index.android.js#L88-L98) right now.

On a positive note, if we go through with this change, adding a radial gradient support will be [a trivial feature](https://developer.apple.com/reference/coregraphics/1455923-cgcontextdrawradialgradient?language=objc).

You can check [ios_context_draw](https://github.com/react-native-community/react-native-linear-gradient/tree/ios_context_draw) branch for a WIP implementation that currently renders the gradient example correctly. I have very limited Obj-C/iOS SDK skills, so your comments and contributions are welcome!:)

@george-cz unfortunately, video tutorial you linked uses CAGradientLayer, so it's also affected by the same problem:(

**Comment by george-cz** [comment] 2017-04-07 11:29
@dgladkov Thanks for the response :)

The video tutorial I posted was to demonstrate, that this is actually a bug in CAGradientLayer implementation.

Thanks for the new branch, its good to know we can resolve this. For now we settled for the CAGradientLayer implementation, as the difference doesn´t really matter for us now. I might come back to this in the future, thanks however!

**Comment by kevinvangelder** [comment] 2017-04-07 17:55
@dgladkov Thanks for verifying! Since we know it's an iOS bug I don't feel bad that the Windows implementation is visibly different. :)

**Comment by scisci** [comment] 2018-01-25 18:16
I know this is old, but just wanted to point out, this is not a bug. iOS clearly states on this page https://developer.apple.com/documentation/quartzcore/cagradientlayer/1462408-startpoint that ` The point is defined in the unit coordinate space and is then mapped to the layer’s bounds rectangle`. So the result is expected.

When you calculate your start and endpoints you have to take the stretching into account based on the aspect ratio of your view.

Something like:
```
// Scale the angle by the aspect ratio
const x = Math.cos(radians);
const y = Math.sin(radians);
const scaledRadians = Math.atan2(y, x / aspectRatio);
```

**Comment by kevinvangelder** [comment] 2018-03-09 23:00
Okay, so then the documentation should just note the behavior so developers can be informed when implementing RNLG on iOS?

**Comment by scisci** [comment] 2018-03-10 05:40
I'm usually trying to imitate some css gradient when I create a gradient, so I would opt for an api that accepts parameters similar to css gradients, but that just may be me.

**Comment by radex** [comment] 2018-11-16 09:49
I think this was solved by recent changes. I'm closing this. Let me know if this is still an issue.

**Closed by radex** 2018-11-16 09:49 UTC
