### ISSUE TITLE
2.0 Error with RN 0.4

### ISSUE THREAD

**Issue by KinanKazmi** [react-native-community/react-native-linear-gradient#142] opened 2017-01-13 17:02 UTC
Im using your component for a dual android/ios project.
Everything was working fine till i upgraded RN to 0.4. Looked here and found new version 2.0. Deleted LinearGradient from package.json and nodemodules and reinstalled it from npm. Got 2.0 and everything but still both android and ios are giving errors.

![screen shot 2017-01-13 at 10 00 07 pm](https://cloud.githubusercontent.com/assets/20215123/21938114/ba4740f2-d9db-11e6-9737-4c6ae0e13956.png)

![screen shot 2017-01-13 at 10 00 23 pm](https://cloud.githubusercontent.com/assets/20215123/21938166/ff3e8d28-d9db-11e6-91f7-60bb0c77ad56.png)

**Comment by dgladkov** [comment] 2017-01-13 20:53
Had the same problem with 0.40.0 upgrade on my project. Please take a look at this diff https://github.com/ncuillery/rn-diff/compare/rn-0.39.2...rn-0.40.0, specifically changes to `ProjectName.xcscheme`. Applying the diff of that file fixed header search problem for me.

**Comment by JulianKingman** [comment] 2017-01-26 16:33
@dgladkov Can you be more specific about what you changed? I'm looking at my settings and I think they match, but I might be missing something.

**Comment by KinanKazmi** [comment] 2017-01-26 18:02
Actually i was using the old style syntax of the component. I read the main page again and changed its style and it worked.
Make sure you are using this syntax
start={{x: 0.0, y: 0.25}} end={{x: 0.5, y: 1.0}}
locations={[0,0.5,0.6]}
And not the old one.

**Comment by dgladkov** [comment] 2017-01-26 20:50
@JulianKingman Updating .xcheme file exactly as it was in the mentioned diff fixed the issue for me. I think specifically it was `parallelizeBuildables = "NO"`.

**Comment by g3r4n** [comment] 2017-01-27 06:24
#144 can fix the issue

**Comment by dgladkov** [comment] 2017-03-30 12:37
The mentioned PR is unrelated as the issue states problem with RN 0.40. The issue is resolved, closing.

**Closed by dgladkov** 2017-03-30 12:37 UTC
